### ISSUE TITLE
Lower dependency target?

### ISSUE THREAD

**Issue by hauntii** [adamzarn/AZVideoPlayer#10]
The minimum version for this package is set as: `.iOS(.v15)`.
I have a very specific case of needing to stay on iOS 14.1 (jailbreakable version)
I figured I'd give it a shot by just lowering the target (`.iOS(.v14)`) in a local copy, and lo and behold, it still works!

Just figured I'd point that out, it'd be nice to receive any future updates to this package if the target was lowered.

Have a nice day!

PS: This dependency saved me greatly! iOS 14.1 VideoPlayers dont work properly, I thank thee!

**Comment by adamzarn** [comment]
@hauntii I updated the minimum version to 14 in this release: https://github.com/adamzarn/AZVideoPlayer/releases/tag/1.3.0
