### ISSUE TITLE
Please create a stable (i.e. tagged) release 

### ISSUE THREAD

**Issue by p4checo** [adamzarn/AZVideoPlayer#7]
Hi!

Thanks for your work on this! 🙏🏼  Could you please create a (tagged) release for this project? Otherwise SPM considers this dependency as unstable when we are pointing to a branch (i.e. `main`) from another package that is used as a stable dependency.

e.g.
- FooApp -> AZVideoPlayer (`main`) ✅ 
- FooApp -> FooSDK(`1.0.0`) -> AZVideoPlayer (`main`) 💥 

Cheers! 🍻

**Comment by adamzarn** [comment]
> Hi!
> 
> Thanks for your work on this! 🙏🏼 Could you please create a (tagged) release for this project? Otherwise SPM considers this dependency as unstable when we are pointing to a branch (i.e. `main`) from another package that is used as a stable dependency.
> 
> e.g.
> 
> * FooApp -> AZVideoPlayer (`main`) ✅
> * FooApp -> FooSDK(`1.0.0`) -> AZVideoPlayer (`main`) 💥
> 
> Cheers! 🍻

I just created release `1.0.0` from the latest commit on `main`. Let me know if that resolves your issue.

**Comment by p4checo** [comment]
Issue sorted! Thank you very much! 🙏🏼
